name: flutter_tts_no_windows
description: A fork of flutter_tts without Windows support (for projects using custom Windows TTS).
version: 1.0.0
homepage: https://github.com/waytoo-average/flutter_tts-fork-for-windows

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tundralabs.fluttertts
        pluginClass: FlutterTtsPlugin
      ios:
        pluginClass: FlutterTtsPlugin
      macos:
        pluginClass: FlutterTtsPlugin
      web:
        pluginClass: FlutterTtsPlugin
        fileName: flutter_tts_web.dart

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.22.0"
dev_dependencies:
  lints: ^3.0.0
